import 'dart:convert';

String safeUriDecode(String input) {
  try {
    return Uri.decodeComponent(input);
  } catch (_) {
    try {
      return Uri.decodeQueryComponent(input);
    } catch (_) {
      return input;
    }
  }
}

Map<String, String> safeSplitQuery(String query) {
  final result = <String, String>{};
  if (query.isEmpty) return result;
  for (final part in query.split('&')) {
    if (part.isEmpty) continue;
    final idx = part.indexOf('=');
    if (idx != -1) {
      final key = safeUriDecode(part.substring(0, idx));
      final val = safeUriDecode(part.substring(idx + 1));
      result[key] = val;
    } else {
      result[safeUriDecode(part)] = '';
    }
  }
  return result;
}

String convertProxyUrisToMihomoYaml(List<String> uris) {
  final proxies = <String>[];
  final names = <String>[];
  final seenNames = <String, int>{};

  int proxyIndex = 1;
  for (int i = 0; i < uris.length; i++) {
    final raw = uris[i].trim();
    if (raw.isEmpty || raw.startsWith('#')) continue;
    var defaultName = 'Proxy $proxyIndex';
    final yaml = _parseProxyUri(raw, defaultName);
    if (yaml.isNotEmpty) {
      var name = _extractName(yaml);
      if (name.isEmpty) name = defaultName;
      if (seenNames.containsKey(name)) {
        seenNames[name] = seenNames[name]! + 1;
        final uniqueName = '$name (${seenNames[name]})';
        final adjustedYaml = yaml.replaceFirst('name: "$name"', 'name: "$uniqueName"');
        proxies.add(adjustedYaml);
        names.add(uniqueName);
      } else {
        seenNames[name] = 1;
        proxies.add(yaml);
        names.add(name);
      }
      proxyIndex++;
    }
  }
  if (proxies.isEmpty) return '';

  final buf = StringBuffer();
  buf.writeln('# Generated by FlClash-Mod Smart Importer');
  buf.writeln('mixed-port: 7890');
  buf.writeln('allow-lan: false');
  buf.writeln('mode: rule');
  buf.writeln('log-level: info');
  buf.writeln('unified-delay: true');
  buf.writeln('tcp-concurrent: true');
  buf.writeln('');
  buf.writeln('dns:');
  buf.writeln('  enable: true');
  buf.writeln('  ipv6: false');
  buf.writeln('  enhanced-mode: fake-ip');
  buf.writeln('  fake-ip-range: 198.18.0.1/16');
  buf.writeln('  nameserver:');
  buf.writeln('    - 77.88.8.8');
  buf.writeln('    - 77.88.8.1');
  buf.writeln('    - 8.8.8.8');
  buf.writeln('    - https://dns.yandex.ru/dns-query');
  buf.writeln('    - https://cloudflare-dns.com/dns-query');
  buf.writeln('');
  buf.writeln('proxies:');
  for (final p in proxies) {
    buf.writeln(p);
  }
  buf.writeln('');
  buf.writeln('proxy-groups:');
  buf.writeln('  - name: PROXY');
  buf.writeln('    type: select');
  buf.writeln('    proxies:');
  for (final n in names) {
    buf.writeln('      - "$n"');
  }
  buf.writeln('      - DIRECT');
  buf.writeln('');
  buf.writeln('rules:');
  buf.writeln('  - MATCH,PROXY');
  return buf.toString();
}

String _extractName(String proxyYaml) {
  for (final line in proxyYaml.split('\n')) {
    var t = line.trim();
    if (t.startsWith('-')) {
      t = t.substring(1).trim();
    }
    if (t.startsWith('name:')) {
      var n = t.substring(5).trim();
      if (n.startsWith('"') && n.endsWith('"') && n.length >= 2) {
        n = n.substring(1, n.length - 1);
      }
      return n;
    }
  }
  return '';
}

String _normalizeFp(String rawFp) {
  final lower = rawFp.trim().toLowerCase();
  if (['chrome', 'firefox', 'safari', 'ios', 'android', 'edge', '360', 'random', 'randomized'].contains(lower)) {
    return lower;
  }
  return 'chrome';
}

String _parseProxyUri(String uri, String defaultName) {
  final lower = uri.toLowerCase();
  try {
    if (lower.startsWith('vmess://')) return _parseVmess(uri, defaultName);
    if (lower.startsWith('vless://')) return _parseVless(uri, defaultName);
    if (lower.startsWith('trojan://')) return _parseTrojan(uri, defaultName);
    if (lower.startsWith('ss://')) return _parseSS(uri, defaultName);
    if (lower.startsWith('hysteria2://') || lower.startsWith('hy2://')) {
      return _parseHysteria2(uri, defaultName);
    }
    if (lower.startsWith('hysteria://')) return _parseHysteria(uri, defaultName);
    if (lower.startsWith('tuic://')) return _parseTuic(uri, defaultName);
  } catch (e) {
    print('Error parsing $uri: $e');
  }
  return '';
}

String _parseVless(String uri, String defaultName) {
  try {
    var raw = uri.substring('vless://'.length);
    String name = defaultName;
    if (raw.contains('#')) {
      final idx = raw.lastIndexOf('#');
      name = _esc(safeUriDecode(raw.substring(idx + 1)).trim());
      raw = raw.substring(0, idx);
    }
    String query = '';
    if (raw.contains('?')) {
      final idx = raw.indexOf('?');
      query = raw.substring(idx + 1);
      raw = raw.substring(0, idx);
    }
    final atIdx = raw.lastIndexOf('@');
    final uuid = raw.substring(0, atIdx);
    final (server, port) = _splitHostPort(raw.substring(atIdx + 1), 443);
    final p = safeSplitQuery(query);
    final type = p['type'] ?? 'tcp';
    final security = p['security'] ?? 'none';
    final flow = p['flow'] ?? '';
    final path = safeUriDecode(p['path'] ?? '/');
    final host = p['host'] ?? '';
    final sni = p['sni'] ?? '';
    final fp = _normalizeFp(p['fp'] ?? 'chrome');
    final pbk = p['pbk'] ?? '';
    final sid = p['sid'] ?? '';
    final grpcSvc = p['serviceName'] ?? '';
    final alpn = p['alpn'] ?? '';
    final insecure = p['insecure'] == '1' || p['allowInsecure'] == '1';

    final sb = StringBuffer();
    sb.writeln('  - name: "$name"');
    sb.writeln('    type: vless');
    sb.writeln('    server: $server');
    sb.writeln('    port: $port');
    sb.writeln('    uuid: $uuid');
    sb.writeln('    udp: true');

    if (type == 'ws') {
      sb.writeln('    network: ws');
      sb.writeln('    ws-opts:');
      sb.writeln('      path: "${_esc(path)}"');
      if (host.isNotEmpty) {
        sb.writeln('      headers:');
        sb.writeln('        Host: $host');
      }
    } else if (type == 'grpc') {
      sb.writeln('    network: grpc');
      sb.writeln('    grpc-opts:');
      sb.writeln('      grpc-service-name: "${_esc(grpcSvc)}"');
    } else if (type == 'h2' || type == 'http') {
      sb.writeln('    network: h2');
      sb.writeln('    h2-opts:');
      sb.writeln('      path: "${_esc(path)}"');
      if (host.isNotEmpty) sb.writeln('      host: [$host]');
    } else {
      sb.writeln('    network: tcp');
      if (flow.isNotEmpty) sb.writeln('    flow: $flow');
    }

    if (security == 'tls') {
      sb.writeln('    tls: true');
      if (sni.isNotEmpty) sb.writeln('    servername: $sni');
      sb.writeln('    client-fingerprint: $fp');
      if (alpn.isNotEmpty) {
        sb.writeln('    alpn:');
        for (final a in alpn.split(',')) {
          if (a.trim().isNotEmpty) sb.writeln('      - ${a.trim()}');
        }
      }
      if (insecure) sb.writeln('    skip-cert-verify: true');
    } else if (security == 'reality') {
      sb.writeln('    tls: true');
      if (sni.isNotEmpty) sb.writeln('    servername: $sni');
      sb.writeln('    client-fingerprint: $fp');
      if (alpn.isNotEmpty) {
        sb.writeln('    alpn:');
        for (final a in alpn.split(',')) {
          if (a.trim().isNotEmpty) sb.writeln('      - ${a.trim()}');
        }
      }
      sb.writeln('    reality-opts:');
      sb.writeln('      public-key: "$pbk"');
      if (sid.isNotEmpty) sb.writeln('      short-id: "$sid"');
    }

    return sb.toString().trimRight();
  } catch (e) {
    print('Vless error: $e');
    return '';
  }
}

String _parseVmess(String uri, String defaultName) {
  try {
    final b64 = uri.substring('vmess://'.length).trim();
    final pad = _padBase64(b64);
    final json = jsonDecode(utf8.decode(base64.decode(pad))) as Map<String, dynamic>;
    final name = _esc(json['ps']?.toString() ?? defaultName);
    final server = json['add']?.toString() ?? '';
    final port = json['port'];
    final uuid = json['id']?.toString() ?? '';
    final alterId = json['aid'] ?? 0;
    final cipher = (json['scy']?.toString().isNotEmpty ?? false) ? json['scy'] : 'auto';
    final network = json['net']?.toString() ?? 'tcp';
    final tls = json['tls']?.toString() == 'tls';
    final sni = json['sni']?.toString() ?? json['host']?.toString() ?? '';
    final path = json['path']?.toString() ?? '/';
    final host = json['host']?.toString() ?? '';
    final alpn = json['alpn']?.toString() ?? '';
    final fp = _normalizeFp(json['fp']?.toString() ?? 'chrome');

    final sb = StringBuffer();
    sb.writeln('  - name: "$name"');
    sb.writeln('    type: vmess');
    sb.writeln('    server: $server');
    sb.writeln('    port: $port');
    sb.writeln('    uuid: $uuid');
    sb.writeln('    alterId: $alterId');
    sb.writeln('    cipher: $cipher');
    sb.writeln('    udp: true');

    if (network == 'ws') {
      sb.writeln('    network: ws');
      sb.writeln('    ws-opts:');
      sb.writeln('      path: "${_esc(path)}"');
      if (host.isNotEmpty) {
        sb.writeln('      headers:');
        sb.writeln('        Host: $host');
      }
    } else if (network == 'grpc') {
      sb.writeln('    network: grpc');
      sb.writeln('    grpc-opts:');
      sb.writeln('      grpc-service-name: "${_esc(path)}"');
    } else if (network == 'h2') {
      sb.writeln('    network: h2');
      sb.writeln('    h2-opts:');
      sb.writeln('      path: "${_esc(path)}"');
      if (host.isNotEmpty) sb.writeln('      host: [$host]');
    } else {
      sb.writeln('    network: tcp');
    }

    if (tls) {
      sb.writeln('    tls: true');
      if (sni.isNotEmpty) sb.writeln('    servername: $sni');
      sb.writeln('    client-fingerprint: $fp');
      if (alpn.isNotEmpty) {
        sb.writeln('    alpn:');
        for (final a in alpn.split(',')) {
          if (a.trim().isNotEmpty) sb.writeln('      - ${a.trim()}');
        }
      }
    }

    return sb.toString().trimRight();
  } catch (_) {
    return '';
  }
}

String _parseTrojan(String uri, String defaultName) {
  try {
    var raw = uri.substring('trojan://'.length);
    String name = defaultName;
    if (raw.contains('#')) {
      final idx = raw.lastIndexOf('#');
      name = _esc(safeUriDecode(raw.substring(idx + 1)).trim());
      raw = raw.substring(0, idx);
    }
    String query = '';
    if (raw.contains('?')) {
      final idx = raw.indexOf('?');
      query = raw.substring(idx + 1);
      raw = raw.substring(0, idx);
    }
    final atIdx = raw.lastIndexOf('@');
    final password = raw.substring(0, atIdx);
    final (server, port) = _splitHostPort(raw.substring(atIdx + 1), 443);
    final p = safeSplitQuery(query);
    final sni = p['sni'] ?? p['peer'] ?? '';
    final type = p['type'] ?? 'tcp';
    final path = safeUriDecode(p['path'] ?? '/');
    final host = p['host'] ?? '';
    final fp = _normalizeFp(p['fp'] ?? 'chrome');
    final alpn = p['alpn'] ?? '';
    final insecure = p['insecure'] == '1' || p['allowInsecure'] == '1';

    final sb = StringBuffer();
    sb.writeln('  - name: "$name"');
    sb.writeln('    type: trojan');
    sb.writeln('    server: $server');
    sb.writeln('    port: $port');
    sb.writeln('    password: "${_esc(password)}"');
    sb.writeln('    udp: true');
    sb.writeln('    tls: true');
    if (sni.isNotEmpty) sb.writeln('    sni: $sni');
    sb.writeln('    client-fingerprint: $fp');
    if (alpn.isNotEmpty) {
      sb.writeln('    alpn:');
      for (final a in alpn.split(',')) {
        if (a.trim().isNotEmpty) sb.writeln('      - ${a.trim()}');
      }
    }
    if (insecure) sb.writeln('    skip-cert-verify: true');

    if (type == 'ws') {
      sb.writeln('    network: ws');
      sb.writeln('    ws-opts:');
      sb.writeln('      path: "${_esc(path)}"');
      if (host.isNotEmpty) {
        sb.writeln('      headers:');
        sb.writeln('        Host: $host');
      }
    } else if (type == 'grpc') {
      sb.writeln('    network: grpc');
      sb.writeln('    grpc-opts:');
      sb.writeln('      grpc-service-name: "${_esc(p['serviceName'] ?? '')}"');
    } else {
      sb.writeln('    network: tcp');
    }
    return sb.toString().trimRight();
  } catch (_) {
    return '';
  }
}

String _parseSS(String uri, String defaultName) {
  try {
    var raw = uri.substring('ss://'.length);
    String name = defaultName;
    if (raw.contains('#')) {
      final idx = raw.lastIndexOf('#');
      name = _esc(safeUriDecode(raw.substring(idx + 1)).trim());
      raw = raw.substring(0, idx);
    }
    if (raw.contains('?')) raw = raw.substring(0, raw.indexOf('?'));
    String method, password, server;
    int port;
    if (raw.contains('@')) {
      final atIdx = raw.lastIndexOf('@');
      final userInfo = raw.substring(0, atIdx);
      final hostPort = raw.substring(atIdx + 1);
      String decoded;
      try {
        decoded = utf8.decode(base64.decode(_padBase64(userInfo)));
      } catch (_) {
        decoded = userInfo;
      }
      final ci = decoded.indexOf(':');
      method = decoded.substring(0, ci);
      password = decoded.substring(ci + 1);
      final hp = _splitHostPort(hostPort, 8388);
      server = hp.$1;
      port = hp.$2;
    } else {
      final decoded = utf8.decode(base64.decode(_padBase64(raw)));
      final ci = decoded.indexOf(':');
      method = decoded.substring(0, ci);
      final rest = decoded.substring(ci + 1);
      final atIdx = rest.lastIndexOf('@');
      password = rest.substring(0, atIdx);
      final hp = _splitHostPort(rest.substring(atIdx + 1), 8388);
      server = hp.$1;
      port = hp.$2;
    }
    final sb = StringBuffer();
    sb.writeln('  - name: "$name"');
    sb.writeln('    type: ss');
    sb.writeln('    server: $server');
    sb.writeln('    port: $port');
    sb.writeln('    cipher: $method');
    sb.writeln('    password: "${_esc(password)}"');
    sb.writeln('    udp: true');
    return sb.toString().trimRight();
  } catch (_) {
    return '';
  }
}

String _parseHysteria2(String uri, String defaultName) {
  try {
    final scheme = uri.toLowerCase().startsWith('hy2://') ? 'hy2://' : 'hysteria2://';
    var raw = uri.substring(scheme.length);
    String name = defaultName;
    if (raw.contains('#')) {
      final idx = raw.lastIndexOf('#');
      name = _esc(safeUriDecode(raw.substring(idx + 1)).trim());
      raw = raw.substring(0, idx);
    }
    String query = '';
    if (raw.contains('?')) {
      final idx = raw.indexOf('?');
      query = raw.substring(idx + 1);
      raw = raw.substring(0, idx);
    }
    String password = '';
    if (raw.contains('@')) {
      final atIdx = raw.lastIndexOf('@');
      password = raw.substring(0, atIdx);
      raw = raw.substring(atIdx + 1);
    }
    final (server, port) = _splitHostPort(raw, 443);
    final p = safeSplitQuery(query);
    final sni = p['sni'] ?? '';
    final insecure = p['insecure'] == '1' || p['allowInsecure'] == '1';
    final sb = StringBuffer();
    sb.writeln('  - name: "$name"');
    sb.writeln('    type: hysteria2');
    sb.writeln('    server: $server');
    sb.writeln('    port: $port');
    sb.writeln('    password: "${_esc(password)}"');
    if (sni.isNotEmpty) sb.writeln('    sni: $sni');
    if (insecure) sb.writeln('    skip-cert-verify: true');
    return sb.toString().trimRight();
  } catch (_) {
    return '';
  }
}

String _parseHysteria(String uri, String defaultName) {
  try {
    var raw = uri.substring('hysteria://'.length);
    String name = defaultName;
    if (raw.contains('#')) {
      final idx = raw.lastIndexOf('#');
      name = _esc(safeUriDecode(raw.substring(idx + 1)).trim());
      raw = raw.substring(0, idx);
    }
    String query = '';
    if (raw.contains('?')) {
      final idx = raw.indexOf('?');
      query = raw.substring(idx + 1);
      raw = raw.substring(0, idx);
    }
    final (server, port) = _splitHostPort(raw, 443);
    final p = safeSplitQuery(query);
    final auth = p['auth'] ?? p['auth_str'] ?? '';
    final sni = p['peer'] ?? p['sni'] ?? '';
    final up = p['upmbps'] ?? p['up'] ?? '100';
    final down = p['downmbps'] ?? p['down'] ?? '100';
    final insecure = p['insecure'] == '1' || p['allowInsecure'] == '1';
    final sb = StringBuffer();
    sb.writeln('  - name: "$name"');
    sb.writeln('    type: hysteria');
    sb.writeln('    server: $server');
    sb.writeln('    port: $port');
    sb.writeln('    auth-str: "${_esc(auth)}"');
    sb.writeln('    up: $up');
    sb.writeln('    down: $down');
    if (sni.isNotEmpty) sb.writeln('    sni: $sni');
    if (insecure) sb.writeln('    skip-cert-verify: true');
    return sb.toString().trimRight();
  } catch (_) {
    return '';
  }
}

String _parseTuic(String uri, String defaultName) {
  try {
    var raw = uri.substring('tuic://'.length);
    String name = defaultName;
    if (raw.contains('#')) {
      final idx = raw.lastIndexOf('#');
      name = _esc(safeUriDecode(raw.substring(idx + 1)).trim());
      raw = raw.substring(0, idx);
    }
    String query = '';
    if (raw.contains('?')) {
      final idx = raw.indexOf('?');
      query = raw.substring(idx + 1);
      raw = raw.substring(0, idx);
    }
    String uuid = '', password = '';
    if (raw.contains('@')) {
      final atIdx = raw.lastIndexOf('@');
      final userInfo = raw.substring(0, atIdx);
      raw = raw.substring(atIdx + 1);
      if (userInfo.contains(':')) {
        final ci = userInfo.indexOf(':');
        uuid = userInfo.substring(0, ci);
        password = userInfo.substring(ci + 1);
      } else {
        uuid = userInfo;
      }
    }
    final (server, port) = _splitHostPort(raw, 443);
    final p = safeSplitQuery(query);
    final sni = p['sni'] ?? '';
    final congestion = p['congestion_control'] ?? 'bbr';
    final sb = StringBuffer();
    sb.writeln('  - name: "$name"');
    sb.writeln('    type: tuic');
    sb.writeln('    server: $server');
    sb.writeln('    port: $port');
    sb.writeln('    uuid: $uuid');
    sb.writeln('    password: "${_esc(password)}"');
    sb.writeln('    congestion-controller: $congestion');
    if (sni.isNotEmpty) sb.writeln('    sni: $sni');
    return sb.toString().trimRight();
  } catch (_) {
    return '';
  }
}

(String, int) _splitHostPort(String hostPort, int defaultPort) {
  if (hostPort.startsWith('[')) {
    final end = hostPort.indexOf(']');
    if (end == -1) return (hostPort, defaultPort);
    final server = hostPort.substring(1, end);
    final rest = hostPort.substring(end + 1);
    return (server, rest.startsWith(':') ? (int.tryParse(rest.substring(1)) ?? defaultPort) : defaultPort);
  }
  final lastColon = hostPort.lastIndexOf(':');
  if (lastColon == -1) return (hostPort, defaultPort);
  return (hostPort.substring(0, lastColon), int.tryParse(hostPort.substring(lastColon + 1)) ?? defaultPort);
}

String _padBase64(String s) {
  final mod = s.length % 4;
  return mod == 0 ? s : s + ('=' * (4 - mod));
}

String _esc(String s) => s.replaceAll('"', '\\"');
